# Appearance
appearance:
  mode: dark
  color: red
  custom_css: ["css/custom.css"]
  font:
    family: "Helvetica, Arial, sans-serif"
    size: "22px"
    weight: "normal"
    line_height: "1.6"


# Site header
header:
  navbar:
    enable: true
    blox: "navbar"
    align: "left"
    fixed_to_top: true
    show_search: true
    show_theme_chooser: false
    color: red
    logo:
      text: "Kateryna's Blog"
      font_family: "Helvetica, Arial, sans-serif"
      font_weight: "bold"
      font_size: "1.5rem"

# Localization
locale:
  date_format: 'Jan 2, 2006'
  time_format: '3:04 PM'

# Site features
features:
  math:
    enable: true
  privacy_pack:
    enable: true
