appearance:
  mode: dark
  color: red
  custom_css: ["css/custom.css"]

header:
  navbar:
    enable: true
    blox: "navbar"
    align: "left"
    fixed_to_top: true
    show_search: true
    show_theme_chooser: false
    logo:
      text: "Kateryna's Blog"

locale:
  date_format: 'Jan 2, 2006'
  time_format: '3:04 PM'

features:
  math:
    enable: true
  privacy_pack:
    enable: true

